#!/bin/bash

project_changes() {
  directory=$1
  git diff HEAD --name-only | grep "^$directory/.*"
}

lint_project() {
  project=$1
  if project_changes $project > /dev/null 2>&1; then
    project_dir="$(git rev-parse --show-toplevel)/$project"
    cd $project_dir
    # Every application is expected to contain a specialised shell script for linting,
    # Each project may have its own set of files/packages to be excluded amongst other customisations.
    if ! scripts/lint.sh; then
      echo -e "\033[1m\033[31mFailed linting, please fix the reported issues\033[0m\n"
      exit 1
    else
      echo -e "\033[1m\033[32mLinting passed, good job!\033[0m\n"
    fi
  else
    echo -e "\033[1m\033[34mNo changes made to source code subject to linting in $project \033[0m\n"
  fi
}

lint_project libs/blueprint
lint_project libs/common
lint_project libs/build-engine

lint_project apps/api
lint_project apps/cli

lint_project runtime/core
lint_project runtime/go
lint_project runtime/java
lint_project runtime/nodejs
lint_project runtime/python
lint_project runtime/rust

lint_project validators/go
lint_project validators/java
lint_project validators/nodejs
lint_project validators/python
lint_project validators/rust
