// Code generated by go generate; DO NOT EDIT.
package env

const (
	// The version of the plugin docgen software.
	pluginDocgenVersion = "dev"
	// The version of the blueprint framework used by the plugin docgen tool.
	blueprintFrameworkVersion = "v0.16.0"
	// The version of the plugin framework used by the plugin docgen tool.
	pluginFrameworkVersion = "v0.0.0-20250515000109-8d2746400999"
)
