//lint:file-ignore SA1019 Ignore as this is generated code

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: deploy-engine/plugin/pluginservice/service.proto

package pluginservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginType is an enum for the type of plugin being registered.
// The plugin type is used to determine the type of plugin that is
// being registered.
type PluginType int32

const (
	// protobuf enums must have a zero value, so we need a NONE value
	// here.
	// PluginType starts at 1.
	PluginType_PLUGIN_TYPE_NONE PluginType = 0
	// A provider plugin.
	PluginType_PLUGIN_TYPE_PROVIDER PluginType = 1
	// A transformer plugin.
	PluginType_PLUGIN_TYPE_TRANSFORMER PluginType = 2
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0: "PLUGIN_TYPE_NONE",
		1: "PLUGIN_TYPE_PROVIDER",
		2: "PLUGIN_TYPE_TRANSFORMER",
	}
	PluginType_value = map[string]int32{
		"PLUGIN_TYPE_NONE":        0,
		"PLUGIN_TYPE_PROVIDER":    1,
		"PLUGIN_TYPE_TRANSFORMER": 2,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_build_engine_plugin_pluginservice_service_proto_enumTypes[0].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_build_engine_plugin_pluginservice_service_proto_enumTypes[0]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginType.Descriptor instead.
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return file_build_engine_plugin_pluginservice_service_proto_rawDescGZIP(), []int{0}
}

// PluginRegistrationRequest is the request
// for registering a plugin.
type PluginRegistrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of plugin that is registered.
	PluginType PluginType `protobuf:"varint,1,opt,name=plugin_type,json=pluginType,enum=plugin.PluginType" json:"plugin_type,omitempty"`
	// The unique identifier for the provider plugin.
	// In addition to being unique, the ID should point to the location
	// where the provider plugin can be downloaded.
	// {hostname/}?{namespace}/{provider}
	//
	// For example:
	// registry.celerityframework.com/celerity/aws
	// celerity/aws
	PluginId string `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId" json:"plugin_id,omitempty"`
	// The id of the plugin instance that should correspond to the
	// id that was captured when the plugin was launched.
	InstanceId string `protobuf:"bytes,3,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	// The protocol version that the plugin is using.
	ProtocolVersion int32 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion" json:"protocol_version,omitempty"`
	// The tcp port that the plugin is listening on.
	// Only the port needs to be specified here as the address
	// can only ever be the loopback address,
	// plugins can not be called from a remote host.
	Port int32 `protobuf:"varint,5,opt,name=port" json:"port,omitempty"`
	// The unix socket that the plugin is listening on.
	UnixSocket string `protobuf:"bytes,6,opt,name=unix_socket,json=unixSocket" json:"unix_socket,omitempty"`
}

func (x *PluginRegistrationRequest) Reset() {
	*x = PluginRegistrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_pluginservice_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRegistrationRequest) ProtoMessage() {}

func (x *PluginRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_pluginservice_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRegistrationRequest.ProtoReflect.Descriptor instead.
func (*PluginRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_pluginservice_service_proto_rawDescGZIP(), []int{0}
}

func (x *PluginRegistrationRequest) GetPluginType() PluginType {
	if x != nil {
		return x.PluginType
	}
	return PluginType_PLUGIN_TYPE_NONE
}

func (x *PluginRegistrationRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginRegistrationRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *PluginRegistrationRequest) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *PluginRegistrationRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PluginRegistrationRequest) GetUnixSocket() string {
	if x != nil {
		return x.UnixSocket
	}
	return ""
}

// PluginRegistrationResponse is the response
// for registering a plugin.
type PluginRegistrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (x *PluginRegistrationResponse) Reset() {
	*x = PluginRegistrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_pluginservice_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRegistrationResponse) ProtoMessage() {}

func (x *PluginRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_pluginservice_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRegistrationResponse.ProtoReflect.Descriptor instead.
func (*PluginRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_pluginservice_service_proto_rawDescGZIP(), []int{1}
}

func (x *PluginRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PluginRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PluginDeregistrationResponse is the request
// for deregistering a plugin.
type PluginDeregistrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the plugin that should correspond to the
	// id that was captured when the plugin was launched.
	PluginId string `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId" json:"plugin_id,omitempty"`
	// The id of the plugin instance that should correspond to the
	// id that was captured when the plugin was launched.
	InstanceId string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (x *PluginDeregistrationRequest) Reset() {
	*x = PluginDeregistrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_pluginservice_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginDeregistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDeregistrationRequest) ProtoMessage() {}

func (x *PluginDeregistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_pluginservice_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginDeregistrationRequest.ProtoReflect.Descriptor instead.
func (*PluginDeregistrationRequest) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_pluginservice_service_proto_rawDescGZIP(), []int{2}
}

func (x *PluginDeregistrationRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginDeregistrationRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// PluginDeregistrationResponse is the response
// for deregistering a plugin.
type PluginDeregistrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (x *PluginDeregistrationResponse) Reset() {
	*x = PluginDeregistrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_pluginservice_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginDeregistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDeregistrationResponse) ProtoMessage() {}

func (x *PluginDeregistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_pluginservice_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginDeregistrationResponse.ProtoReflect.Descriptor instead.
func (*PluginDeregistrationResponse) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_pluginservice_service_proto_rawDescGZIP(), []int{3}
}

func (x *PluginDeregistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PluginDeregistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_build_engine_plugin_pluginservice_service_proto protoreflect.FileDescriptor

var file_build_engine_plugin_pluginservice_service_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x22, 0xee, 0x01, 0x0a, 0x19, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0b, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x69,
	0x78, 0x5f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x75, 0x6e, 0x69, 0x78, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x50, 0x0a, 0x1a, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5b, 0x0a, 0x1b,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x44, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x1c, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x44, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x59, 0x0a,
	0x0a, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x50,
	0x4c, 0x55, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x4c, 0x55, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x50,
	0x4c, 0x55, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53,
	0x46, 0x4f, 0x52, 0x4d, 0x45, 0x52, 0x10, 0x02, 0x32, 0xb9, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x21, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0a, 0x44, 0x65, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x44, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x44, 0x65, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x4d, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x77, 0x6f, 0x2d, 0x68, 0x75, 0x6e, 0x64, 0x72, 0x65, 0x64, 0x2f, 0x63,
	0x65, 0x6c, 0x65, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x92, 0x03,
	0x02, 0x08, 0x02, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
}

var (
	file_build_engine_plugin_pluginservice_service_proto_rawDescOnce sync.Once
	file_build_engine_plugin_pluginservice_service_proto_rawDescData = file_build_engine_plugin_pluginservice_service_proto_rawDesc
)

func file_build_engine_plugin_pluginservice_service_proto_rawDescGZIP() []byte {
	file_build_engine_plugin_pluginservice_service_proto_rawDescOnce.Do(func() {
		file_build_engine_plugin_pluginservice_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_build_engine_plugin_pluginservice_service_proto_rawDescData)
	})
	return file_build_engine_plugin_pluginservice_service_proto_rawDescData
}

var file_build_engine_plugin_pluginservice_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_build_engine_plugin_pluginservice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_build_engine_plugin_pluginservice_service_proto_goTypes = []interface{}{
	(PluginType)(0),                      // 0: plugin.PluginType
	(*PluginRegistrationRequest)(nil),    // 1: plugin.PluginRegistrationRequest
	(*PluginRegistrationResponse)(nil),   // 2: plugin.PluginRegistrationResponse
	(*PluginDeregistrationRequest)(nil),  // 3: plugin.PluginDeregistrationRequest
	(*PluginDeregistrationResponse)(nil), // 4: plugin.PluginDeregistrationResponse
}
var file_build_engine_plugin_pluginservice_service_proto_depIdxs = []int32{
	0, // 0: plugin.PluginRegistrationRequest.plugin_type:type_name -> plugin.PluginType
	1, // 1: plugin.Service.Register:input_type -> plugin.PluginRegistrationRequest
	3, // 2: plugin.Service.Deregister:input_type -> plugin.PluginDeregistrationRequest
	2, // 3: plugin.Service.Register:output_type -> plugin.PluginRegistrationResponse
	4, // 4: plugin.Service.Deregister:output_type -> plugin.PluginDeregistrationResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_build_engine_plugin_pluginservice_service_proto_init() }
func file_build_engine_plugin_pluginservice_service_proto_init() {
	if File_build_engine_plugin_pluginservice_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_build_engine_plugin_pluginservice_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginRegistrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_pluginservice_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginRegistrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_pluginservice_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginDeregistrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_pluginservice_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginDeregistrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_build_engine_plugin_pluginservice_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_build_engine_plugin_pluginservice_service_proto_goTypes,
		DependencyIndexes: file_build_engine_plugin_pluginservice_service_proto_depIdxs,
		EnumInfos:         file_build_engine_plugin_pluginservice_service_proto_enumTypes,
		MessageInfos:      file_build_engine_plugin_pluginservice_service_proto_msgTypes,
	}.Build()
	File_build_engine_plugin_pluginservice_service_proto = out.File
	file_build_engine_plugin_pluginservice_service_proto_rawDesc = nil
	file_build_engine_plugin_pluginservice_service_proto_goTypes = nil
	file_build_engine_plugin_pluginservice_service_proto_depIdxs = nil
}
