// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: build-engine/plugin/providerserverv1/provider.proto

package providerserverv1

import (
	schemapb "github.com/two-hundred/celerity/libs/blueprint/schemapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DiagnosticLevel is an enum for the level of a diagnostic.
type DiagnosticLevel int32

const (
	// protobuf enums must have a zero value, so we need a NONE value
	// here.
	// DiagnosticLevel starts at 1 as per the Blueprint framework.
	DiagnosticLevel_DIAGNOSTIC_LEVEL_NONE DiagnosticLevel = 0
	// Indicates an error diagnostic.
	DiagnosticLevel_DIAGNOSTIC_LEVEL_ERROR DiagnosticLevel = 1
	// Indicates a warning diagnostic.
	DiagnosticLevel_DIAGNOSTIC_LEVEL_WARNING DiagnosticLevel = 2
	// Indicates an informational diagnostic.
	DiagnosticLevel_DIAGNOSTIC_LEVEL_INFO DiagnosticLevel = 3
)

// Enum value maps for DiagnosticLevel.
var (
	DiagnosticLevel_name = map[int32]string{
		0: "DIAGNOSTIC_LEVEL_NONE",
		1: "DIAGNOSTIC_LEVEL_ERROR",
		2: "DIAGNOSTIC_LEVEL_WARNING",
		3: "DIAGNOSTIC_LEVEL_INFO",
	}
	DiagnosticLevel_value = map[string]int32{
		"DIAGNOSTIC_LEVEL_NONE":    0,
		"DIAGNOSTIC_LEVEL_ERROR":   1,
		"DIAGNOSTIC_LEVEL_WARNING": 2,
		"DIAGNOSTIC_LEVEL_INFO":    3,
	}
)

func (x DiagnosticLevel) Enum() *DiagnosticLevel {
	p := new(DiagnosticLevel)
	*p = x
	return p
}

func (x DiagnosticLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiagnosticLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_build_engine_plugin_providerserverv1_provider_proto_enumTypes[0].Descriptor()
}

func (DiagnosticLevel) Type() protoreflect.EnumType {
	return &file_build_engine_plugin_providerserverv1_provider_proto_enumTypes[0]
}

func (x DiagnosticLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiagnosticLevel.Descriptor instead.
func (DiagnosticLevel) EnumDescriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{0}
}

// DiagnosticLevel is an enum for the level of a diagnostic.
type ColumnAccuracy int32

const (
	// protobuf enums must have a zero value, so we need a NONE value
	// here.
	// ColumnAccuracy starts at 1 as per the Blueprint framework.
	ColumnAccuracy_COLUMN_ACCURACY_NONE ColumnAccuracy = 0
	// Indicates that the column is accurate.
	ColumnAccuracy_COLUMN_ACCURACY_EXACT ColumnAccuracy = 1
	// Indicates that the column is approximate.
	ColumnAccuracy_COLUMN_ACCURACY_APPROXIMATE ColumnAccuracy = 2
)

// Enum value maps for ColumnAccuracy.
var (
	ColumnAccuracy_name = map[int32]string{
		0: "COLUMN_ACCURACY_NONE",
		1: "COLUMN_ACCURACY_EXACT",
		2: "COLUMN_ACCURACY_APPROXIMATE",
	}
	ColumnAccuracy_value = map[string]int32{
		"COLUMN_ACCURACY_NONE":        0,
		"COLUMN_ACCURACY_EXACT":       1,
		"COLUMN_ACCURACY_APPROXIMATE": 2,
	}
)

func (x ColumnAccuracy) Enum() *ColumnAccuracy {
	p := new(ColumnAccuracy)
	*p = x
	return p
}

func (x ColumnAccuracy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnAccuracy) Descriptor() protoreflect.EnumDescriptor {
	return file_build_engine_plugin_providerserverv1_provider_proto_enumTypes[1].Descriptor()
}

func (ColumnAccuracy) Type() protoreflect.EnumType {
	return &file_build_engine_plugin_providerserverv1_provider_proto_enumTypes[1]
}

func (x ColumnAccuracy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnAccuracy.Descriptor instead.
func (ColumnAccuracy) EnumDescriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{1}
}

// ErrorCode is an enum for a range of error codes
// for provider plugins.
type ErrorCode int32

const (
	// Indicates that the error is unexpected and the
	// action cannot be retried by the build engine
	// host.
	// This will not crash the build engine host but
	// will stop the current action (e.g. deploying a blueprint).
	ErrorCode_ERROR_CODE_UNEXPECTED ErrorCode = 0
	// Indicates that the failure is transient and the
	// action can be retried by the build engine
	// host based on the build engine host's retry policy.
	ErrorCode_ERROR_CODE_TRANSIENT ErrorCode = 1
	// Indicates that the input to the provider plugin
	// is invalid. Bad input errors should not be retried
	// but are distinguished from unexpected errors to allow
	// the build engine host to provide a more specific
	// error message to the user.
	ErrorCode_ERROR_CODE_BAD_INPUT ErrorCode = 2
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNEXPECTED",
		1: "ERROR_CODE_TRANSIENT",
		2: "ERROR_CODE_BAD_INPUT",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNEXPECTED": 0,
		"ERROR_CODE_TRANSIENT":  1,
		"ERROR_CODE_BAD_INPUT":  2,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_build_engine_plugin_providerserverv1_provider_proto_enumTypes[2].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_build_engine_plugin_providerserverv1_provider_proto_enumTypes[2]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{2}
}

// Namespace of a provider used to route resource and data source types
// to the correct provider.
type Namespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *Namespace) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// ValidateResourceRequest is the request
// for resource validation.
type ValidateResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The resource schema as parsed within a blueprint.
	SchemaResource *schemapb.Resource `protobuf:"bytes,1,opt,name=schema_resource,json=schemaResource" json:"schema_resource,omitempty"`
	// Runtime parameters for the current blueprint,
	// provider and context.
	BlueprintParams *BlueprintParams `protobuf:"bytes,2,opt,name=blueprint_params,json=blueprintParams" json:"blueprint_params,omitempty"`
}

func (x *ValidateResourceRequest) Reset() {
	*x = ValidateResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResourceRequest) ProtoMessage() {}

func (x *ValidateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResourceRequest.ProtoReflect.Descriptor instead.
func (*ValidateResourceRequest) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResourceRequest) GetSchemaResource() *schemapb.Resource {
	if x != nil {
		return x.SchemaResource
	}
	return nil
}

func (x *ValidateResourceRequest) GetBlueprintParams() *BlueprintParams {
	if x != nil {
		return x.BlueprintParams
	}
	return nil
}

// ValidateResourceResponse is the response
// for resource validation, can be a validation
// complete response or an error response.
type ValidateResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*ValidateResourceResponse_CompleteResponse
	//	*ValidateResourceResponse_ErrorResponse
	Response isValidateResourceResponse_Response `protobuf_oneof:"response"`
}

func (x *ValidateResourceResponse) Reset() {
	*x = ValidateResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResourceResponse) ProtoMessage() {}

func (x *ValidateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResourceResponse.ProtoReflect.Descriptor instead.
func (*ValidateResourceResponse) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{2}
}

func (m *ValidateResourceResponse) GetResponse() isValidateResourceResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ValidateResourceResponse) GetCompleteResponse() *ValidateResourceCompleteResponse {
	if x, ok := x.GetResponse().(*ValidateResourceResponse_CompleteResponse); ok {
		return x.CompleteResponse
	}
	return nil
}

func (x *ValidateResourceResponse) GetErrorResponse() *ErrorResponse {
	if x, ok := x.GetResponse().(*ValidateResourceResponse_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

type isValidateResourceResponse_Response interface {
	isValidateResourceResponse_Response()
}

type ValidateResourceResponse_CompleteResponse struct {
	CompleteResponse *ValidateResourceCompleteResponse `protobuf:"bytes,1,opt,name=complete_response,json=completeResponse,oneof"`
}

type ValidateResourceResponse_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,2,opt,name=error_response,json=errorResponse,oneof"`
}

func (*ValidateResourceResponse_CompleteResponse) isValidateResourceResponse_Response() {}

func (*ValidateResourceResponse_ErrorResponse) isValidateResourceResponse_Response() {}

// ValidateResourceCompleteResponse is the response
// returned by the provider plugin when resource
// validation has been completed.
type ValidateResourceCompleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diagnostics []*Diagnostic `protobuf:"bytes,1,rep,name=diagnostics" json:"diagnostics,omitempty"`
}

func (x *ValidateResourceCompleteResponse) Reset() {
	*x = ValidateResourceCompleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateResourceCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResourceCompleteResponse) ProtoMessage() {}

func (x *ValidateResourceCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResourceCompleteResponse.ProtoReflect.Descriptor instead.
func (*ValidateResourceCompleteResponse) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateResourceCompleteResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

// Diagnostic provides error, warning or informational
// diagnostic for a blueprint.
type Diagnostic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The level of this diagnostic.
	Level DiagnosticLevel `protobuf:"varint,1,opt,name=level,enum=providerserverv1.DiagnosticLevel" json:"level,omitempty"`
	// The message of this diagnostic.
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// An optional text range in the source blueprint
	// that the diagnostic applies to.
	// This will only be present when the source blueprint
	// is YAML and the plugin can extract this information
	// from the resource schema.
	Range *DiagnosticRange `protobuf:"bytes,3,opt,name=range" json:"range,omitempty"`
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *Diagnostic) GetLevel() DiagnosticLevel {
	if x != nil {
		return x.Level
	}
	return DiagnosticLevel_DIAGNOSTIC_LEVEL_NONE
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetRange() *DiagnosticRange {
	if x != nil {
		return x.Range
	}
	return nil
}

// A range in the source blueprint that a diagnostic applies to.
// This will only be used for source formats that allow position tracking
// (i.e. YAML source documents).
type DiagnosticRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start          *SourceMeta    `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	End            *SourceMeta    `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
	ColumnAccuracy ColumnAccuracy `protobuf:"varint,3,opt,name=column_accuracy,json=columnAccuracy,enum=providerserverv1.ColumnAccuracy" json:"column_accuracy,omitempty"`
}

func (x *DiagnosticRange) Reset() {
	*x = DiagnosticRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiagnosticRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticRange) ProtoMessage() {}

func (x *DiagnosticRange) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticRange.ProtoReflect.Descriptor instead.
func (*DiagnosticRange) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *DiagnosticRange) GetStart() *SourceMeta {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *DiagnosticRange) GetEnd() *SourceMeta {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *DiagnosticRange) GetColumnAccuracy() ColumnAccuracy {
	if x != nil {
		return x.ColumnAccuracy
	}
	return ColumnAccuracy_COLUMN_ACCURACY_NONE
}

// SourceMeta provides the line and column number in the source blueprint.
type SourceMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The line number in the source blueprint.
	Line int32 `protobuf:"varint,1,opt,name=line" json:"line,omitempty"`
	// The column number in the source blueprint.
	Column int32 `protobuf:"varint,2,opt,name=column" json:"column,omitempty"`
}

func (x *SourceMeta) Reset() {
	*x = SourceMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceMeta) ProtoMessage() {}

func (x *SourceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceMeta.ProtoReflect.Descriptor instead.
func (*SourceMeta) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *SourceMeta) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *SourceMeta) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// Error response returned by the provider plugin
// when an error occurs during any of the supported
// provider plugin actions.
type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An error code specific to the plugin system.
	// For example, an action that should be retried
	// would have a specific error code to let the build engine
	// host know that the action should be retried.
	Code ErrorCode `protobuf:"varint,1,opt,name=code,enum=providerserverv1.ErrorCode" json:"code,omitempty"`
	// A human-readable error message.
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// Extra details about the error.
	Details *anypb.Any `protobuf:"bytes,3,opt,name=details" json:"details,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNEXPECTED
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

// BlueprintParams holds the runtime parameters for
// the current blueprint, provider and context.
type BlueprintParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Configuration parameters specifically for the provider.
	ProviderConfig map[string]*schemapb.ScalarValue `protobuf:"bytes,1,rep,name=provider_config,json=providerConfig" json:"provider_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Context-wide variable for the current build engine run.
	ContextVariables map[string]*schemapb.ScalarValue `protobuf:"bytes,2,rep,name=context_variables,json=contextVariables" json:"context_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Variables for the current blueprint.
	BlueprintVariables map[string]*schemapb.ScalarValue `protobuf:"bytes,3,rep,name=blueprint_variables,json=blueprintVariables" json:"blueprint_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *BlueprintParams) Reset() {
	*x = BlueprintParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlueprintParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlueprintParams) ProtoMessage() {}

func (x *BlueprintParams) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlueprintParams.ProtoReflect.Descriptor instead.
func (*BlueprintParams) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *BlueprintParams) GetProviderConfig() map[string]*schemapb.ScalarValue {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *BlueprintParams) GetContextVariables() map[string]*schemapb.ScalarValue {
	if x != nil {
		return x.ContextVariables
	}
	return nil
}

func (x *BlueprintParams) GetBlueprintVariables() map[string]*schemapb.ScalarValue {
	if x != nil {
		return x.BlueprintVariables
	}
	return nil
}

// ResourceInfo holds identifiers for the current resource instance
// along with the resource schema.
type ResourceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Holds the ID of a resource when in the context
	// of a blueprint instance when deploying or staging changes.
	// Sometimes staging changes is independent of an instance and is used to compare
	// two vesions of a blueprint in which
	// case the resource ID will be empty.
	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
	// Holds the ID of the blueprint instance
	// that the current resource belongs to.
	InstanceId string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	// Holds the ID of the blueprint instance revision
	// that the current resource deployment belongs to.
	RevisionId string `protobuf:"bytes,3,opt,name=revision_id,json=revisionId" json:"revision_id,omitempty"`
	// The resource schema as parsed within a blueprint.
	SchemaResource *schemapb.Resource `protobuf:"bytes,4,opt,name=schema_resource,json=schemaResource" json:"schema_resource,omitempty"`
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceInfo) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourceInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ResourceInfo) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *ResourceInfo) GetSchemaResource() *schemapb.Resource {
	if x != nil {
		return x.SchemaResource
	}
	return nil
}

// The type of resource to carry out an action or query
// some information about.
type ResourceType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (x *ResourceType) Reset() {
	*x = ResourceType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceType) ProtoMessage() {}

func (x *ResourceType) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceType.ProtoReflect.Descriptor instead.
func (*ResourceType) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *ResourceType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// CanLinkToResponse is the response
// for a request to get all the resource types
// that a given resource type can link to.
type CanLinkToResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceTypes []*ResourceType `protobuf:"bytes,1,rep,name=resource_types,json=resourceTypes" json:"resource_types,omitempty"`
}

func (x *CanLinkToResponse) Reset() {
	*x = CanLinkToResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanLinkToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanLinkToResponse) ProtoMessage() {}

func (x *CanLinkToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanLinkToResponse.ProtoReflect.Descriptor instead.
func (*CanLinkToResponse) Descriptor() ([]byte, []int) {
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *CanLinkToResponse) GetResourceTypes() []*ResourceType {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

var File_build_engine_plugin_providerserverv1_provider_proto protoreflect.FileDescriptor

var file_build_engine_plugin_providerserverv1_provider_proto_rawDesc = []byte{
	0x0a, 0x33, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x16, 0x62, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x17, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39,
	0x0a, 0x0f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x0e, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x10, 0x62, 0x6c, 0x75,
	0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x0f, 0x62, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0xd3, 0x01, 0x0a, 0x18, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x32, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0e, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x62, 0x0a,
	0x20, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f,
	0x73, 0x74, 0x69, 0x63, 0x52, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x22, 0x98, 0x01, 0x0a, 0x0a, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63,
	0x12, 0x37, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x21, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x76, 0x31, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x22, 0xc0, 0x01, 0x0a,
	0x0f, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x32, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x76, 0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x2e, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x03, 0x65, 0x6e, 0x64, 0x12, 0x49, 0x0a, 0x0f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x61,
	0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x52,
	0x0e, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x22,
	0x38, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x8a, 0x01, 0x0a, 0x0d, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xd1, 0x04, 0x0a, 0x0f, 0x42, 0x6c, 0x75, 0x65, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x5e, 0x0a, 0x0f, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x64, 0x0a, 0x11, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69,
	0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x10,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x12, 0x6a, 0x0a, 0x13, 0x62, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x76, 0x31,
	0x2e, 0x42, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x2e, 0x42, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x12, 0x62, 0x6c, 0x75, 0x65, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x1a, 0x56, 0x0a, 0x13,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x53, 0x63,
	0x61, 0x6c, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x1a, 0x58, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x5a,
	0x0a, 0x17, 0x42, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xac, 0x01, 0x0a, 0x0c, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x39,
	0x0a, 0x0f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x0e, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x5a, 0x0a,
	0x11, 0x43, 0x61, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x45, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2a, 0x81, 0x01, 0x0a, 0x0f, 0x44, 0x69,
	0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x19, 0x0a,
	0x15, 0x44, 0x49, 0x41, 0x47, 0x4e, 0x4f, 0x53, 0x54, 0x49, 0x43, 0x5f, 0x4c, 0x45, 0x56, 0x45,
	0x4c, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x44, 0x49, 0x41, 0x47,
	0x4e, 0x4f, 0x53, 0x54, 0x49, 0x43, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x44, 0x49, 0x41, 0x47, 0x4e, 0x4f, 0x53, 0x54,
	0x49, 0x43, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47,
	0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x49, 0x41, 0x47, 0x4e, 0x4f, 0x53, 0x54, 0x49, 0x43,
	0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x03, 0x2a, 0x66, 0x0a,
	0x0e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x12,
	0x18, 0x0a, 0x14, 0x43, 0x4f, 0x4c, 0x55, 0x4d, 0x4e, 0x5f, 0x41, 0x43, 0x43, 0x55, 0x52, 0x41,
	0x43, 0x59, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4c,
	0x55, 0x4d, 0x4e, 0x5f, 0x41, 0x43, 0x43, 0x55, 0x52, 0x41, 0x43, 0x59, 0x5f, 0x45, 0x58, 0x41,
	0x43, 0x54, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x4f, 0x4c, 0x55, 0x4d, 0x4e, 0x5f, 0x41,
	0x43, 0x43, 0x55, 0x52, 0x41, 0x43, 0x59, 0x5f, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x58, 0x49, 0x4d,
	0x41, 0x54, 0x45, 0x10, 0x02, 0x2a, 0x5a, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45,
	0x5f, 0x55, 0x4e, 0x45, 0x58, 0x50, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a,
	0x14, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x4e,
	0x53, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x42, 0x41, 0x44, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x10,
	0x02, 0x32, 0x92, 0x02, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x45,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x10, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x52, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x12,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x1a,
	0x23, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x50, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x77, 0x6f, 0x2d, 0x68, 0x75, 0x6e, 0x64, 0x72, 0x65, 0x64,
	0x2f, 0x63, 0x65, 0x6c, 0x65, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x76, 0x31, 0x92, 0x03, 0x02, 0x08, 0x02, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x70, 0xe8, 0x07,
}

var (
	file_build_engine_plugin_providerserverv1_provider_proto_rawDescOnce sync.Once
	file_build_engine_plugin_providerserverv1_provider_proto_rawDescData = file_build_engine_plugin_providerserverv1_provider_proto_rawDesc
)

func file_build_engine_plugin_providerserverv1_provider_proto_rawDescGZIP() []byte {
	file_build_engine_plugin_providerserverv1_provider_proto_rawDescOnce.Do(func() {
		file_build_engine_plugin_providerserverv1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(file_build_engine_plugin_providerserverv1_provider_proto_rawDescData)
	})
	return file_build_engine_plugin_providerserverv1_provider_proto_rawDescData
}

var file_build_engine_plugin_providerserverv1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_build_engine_plugin_providerserverv1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_build_engine_plugin_providerserverv1_provider_proto_goTypes = []interface{}{
	(DiagnosticLevel)(0),                     // 0: providerserverv1.DiagnosticLevel
	(ColumnAccuracy)(0),                      // 1: providerserverv1.ColumnAccuracy
	(ErrorCode)(0),                           // 2: providerserverv1.ErrorCode
	(*Namespace)(nil),                        // 3: providerserverv1.Namespace
	(*ValidateResourceRequest)(nil),          // 4: providerserverv1.ValidateResourceRequest
	(*ValidateResourceResponse)(nil),         // 5: providerserverv1.ValidateResourceResponse
	(*ValidateResourceCompleteResponse)(nil), // 6: providerserverv1.ValidateResourceCompleteResponse
	(*Diagnostic)(nil),                       // 7: providerserverv1.Diagnostic
	(*DiagnosticRange)(nil),                  // 8: providerserverv1.DiagnosticRange
	(*SourceMeta)(nil),                       // 9: providerserverv1.SourceMeta
	(*ErrorResponse)(nil),                    // 10: providerserverv1.ErrorResponse
	(*BlueprintParams)(nil),                  // 11: providerserverv1.BlueprintParams
	(*ResourceInfo)(nil),                     // 12: providerserverv1.ResourceInfo
	(*ResourceType)(nil),                     // 13: providerserverv1.ResourceType
	(*CanLinkToResponse)(nil),                // 14: providerserverv1.CanLinkToResponse
	nil,                                      // 15: providerserverv1.BlueprintParams.ProviderConfigEntry
	nil,                                      // 16: providerserverv1.BlueprintParams.ContextVariablesEntry
	nil,                                      // 17: providerserverv1.BlueprintParams.BlueprintVariablesEntry
	(*schemapb.Resource)(nil),                // 18: schema.Resource
	(*anypb.Any)(nil),                        // 19: google.protobuf.Any
	(*schemapb.ScalarValue)(nil),             // 20: schema.ScalarValue
	(*emptypb.Empty)(nil),                    // 21: google.protobuf.Empty
}
var file_build_engine_plugin_providerserverv1_provider_proto_depIdxs = []int32{
	18, // 0: providerserverv1.ValidateResourceRequest.schema_resource:type_name -> schema.Resource
	11, // 1: providerserverv1.ValidateResourceRequest.blueprint_params:type_name -> providerserverv1.BlueprintParams
	6,  // 2: providerserverv1.ValidateResourceResponse.complete_response:type_name -> providerserverv1.ValidateResourceCompleteResponse
	10, // 3: providerserverv1.ValidateResourceResponse.error_response:type_name -> providerserverv1.ErrorResponse
	7,  // 4: providerserverv1.ValidateResourceCompleteResponse.diagnostics:type_name -> providerserverv1.Diagnostic
	0,  // 5: providerserverv1.Diagnostic.level:type_name -> providerserverv1.DiagnosticLevel
	8,  // 6: providerserverv1.Diagnostic.range:type_name -> providerserverv1.DiagnosticRange
	9,  // 7: providerserverv1.DiagnosticRange.start:type_name -> providerserverv1.SourceMeta
	9,  // 8: providerserverv1.DiagnosticRange.end:type_name -> providerserverv1.SourceMeta
	1,  // 9: providerserverv1.DiagnosticRange.column_accuracy:type_name -> providerserverv1.ColumnAccuracy
	2,  // 10: providerserverv1.ErrorResponse.code:type_name -> providerserverv1.ErrorCode
	19, // 11: providerserverv1.ErrorResponse.details:type_name -> google.protobuf.Any
	15, // 12: providerserverv1.BlueprintParams.provider_config:type_name -> providerserverv1.BlueprintParams.ProviderConfigEntry
	16, // 13: providerserverv1.BlueprintParams.context_variables:type_name -> providerserverv1.BlueprintParams.ContextVariablesEntry
	17, // 14: providerserverv1.BlueprintParams.blueprint_variables:type_name -> providerserverv1.BlueprintParams.BlueprintVariablesEntry
	18, // 15: providerserverv1.ResourceInfo.schema_resource:type_name -> schema.Resource
	13, // 16: providerserverv1.CanLinkToResponse.resource_types:type_name -> providerserverv1.ResourceType
	20, // 17: providerserverv1.BlueprintParams.ProviderConfigEntry.value:type_name -> schema.ScalarValue
	20, // 18: providerserverv1.BlueprintParams.ContextVariablesEntry.value:type_name -> schema.ScalarValue
	20, // 19: providerserverv1.BlueprintParams.BlueprintVariablesEntry.value:type_name -> schema.ScalarValue
	21, // 20: providerserverv1.Provider.GetNamespace:input_type -> google.protobuf.Empty
	4,  // 21: providerserverv1.Provider.ValidateResource:input_type -> providerserverv1.ValidateResourceRequest
	13, // 22: providerserverv1.Provider.CanLinkTo:input_type -> providerserverv1.ResourceType
	3,  // 23: providerserverv1.Provider.GetNamespace:output_type -> providerserverv1.Namespace
	5,  // 24: providerserverv1.Provider.ValidateResource:output_type -> providerserverv1.ValidateResourceResponse
	14, // 25: providerserverv1.Provider.CanLinkTo:output_type -> providerserverv1.CanLinkToResponse
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_build_engine_plugin_providerserverv1_provider_proto_init() }
func file_build_engine_plugin_providerserverv1_provider_proto_init() {
	if File_build_engine_plugin_providerserverv1_provider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateResourceCompleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diagnostic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiagnosticRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlueprintParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CanLinkToResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_build_engine_plugin_providerserverv1_provider_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ValidateResourceResponse_CompleteResponse)(nil),
		(*ValidateResourceResponse_ErrorResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_build_engine_plugin_providerserverv1_provider_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_build_engine_plugin_providerserverv1_provider_proto_goTypes,
		DependencyIndexes: file_build_engine_plugin_providerserverv1_provider_proto_depIdxs,
		EnumInfos:         file_build_engine_plugin_providerserverv1_provider_proto_enumTypes,
		MessageInfos:      file_build_engine_plugin_providerserverv1_provider_proto_msgTypes,
	}.Build()
	File_build_engine_plugin_providerserverv1_provider_proto = out.File
	file_build_engine_plugin_providerserverv1_provider_proto_rawDesc = nil
	file_build_engine_plugin_providerserverv1_provider_proto_goTypes = nil
	file_build_engine_plugin_providerserverv1_provider_proto_depIdxs = nil
}
